### ISSUE TITLE
Injecting failure

### ISSUE THREAD

**Issue by MrWhiteGoat** [aixxe/csgo-bhop-linux#1]
Getting an error while trying to inject.
`ptrace(PTRACE_GETSIGINFO) failed`

Using linux-inject
Really new to csgo cheating and shit so.

**Comment by aixxe** [comment]
Personally had no success with linux-inject either. [Try using gdb](https://aixxe.net/2016/09/shared-library-injection) or hotpacher instead.

**Comment by MrWhiteGoat** [comment]
Tried gdp
Getting this error.
`(gdb) attach 13318
Attaching to process 13318
[New LWP 13320]
[New LWP 13321]
[New LWP 13322]
[New LWP 13323]
[New LWP 13324]
[New LWP 13331]
[New LWP 13337]
[New LWP 13338]
[New LWP 13339]
[New LWP 13340]
[New LWP 13342]
[New LWP 13343]
[New LWP 13344]
[New LWP 13345]
[New LWP 13347]
[New LWP 13348]
[New LWP 13349]
[New LWP 13366]
[New LWP 13368]
[New LWP 13372]
[New LWP 13381]
warning: Could not load shared library symbols for bin/linux64/launcher_client.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fb138696f1c in __lll_lock_wait () from /usr/lib/libpthread.so.0
`

**Comment by aixxe** [comment]
That's expected, it's not an error. You can see I get [similar output in my tutorial](https://cdn.aixxe.net/blog/uploads/2/attach.jpg).

What happened after you did that?

**Comment by MrWhiteGoat** [comment]
Game freezes. Maybe I can't run it in fullscreen?

**Comment by aixxe** [comment]
It should freeze, you have to type `continue` after that.

**Comment by MrWhiteGoat** [comment]
Oh. Me being an idiot xd.
You ever did a low fov aimbot before?
My goal atm.

**Comment by aixxe** [comment]
After you've [hooked CreateMove](https://aixxe.net/2016/09/createmove-linux-csgo) the rest should be the same as Windows. Plenty of source available to create something like that. Personally I won't be releasing any cheats though.

**Comment by MrWhiteGoat** [comment]
Ayy, one more question :)
I'm trying to setup linuxbasehook by atex, though it doesn't draw any strings.
(without modification it should say "Linux Basehook by Atex")
Any solution?

**Comment by aixxe** [comment]
It won't work out of the box. I can't remember what I did to fix it but the whole thing is a mess so I quickly started writing my own base instead. If you want help for that project I'd suggest posting in the forum thread instead.
